hibernate.connection.driver_class=oracle.jdbc.OracleDriver
hibernate.connection.dataSourceClassName=oracle.jdbc.pool.OracleDataSource
#hibernate.connection.url=jdbc:oracle:thin:@//92.205.108.111:1521/lehaa.abc.net	
hibernate.connection.url=jdbc:oracle:thin:@//localhost:1521/orcl	
hibernate.connection.username=fours_payroll
hibernate.connection.password=fours_payroll
hibernate.defaultSchema=fours_payroll
hibernate.hql.bulk_id_strategy=org.hibernate.hql.spi.id.inline.InlineIdsOrClauseBulkIdStrategy

#hibernate.hikari.minimumIdle=2
#hibernate.hikari.maxLifetime=18000
#hibernate.hikari.maximumPoolSize=6
#hibernate.hikari.idleTimeout=600
#hibernate.hikari.connectionTimeout=30000
#hibernate.hikari.validationTimeout=120000


hibernate.hikari.validationTimeout=5000

hibernate.hikari.maximumPoolSize=30
hibernate.hikari.minimumIdle=5
hibernate.hikari.idleTimeout=30000
hibernate.hikari.maxLifetime=1800000
hibernate.hikari.connectionTimeout=30000

hibernate.hikari.leakDetectionThreshold=20000
# 60 seconds

javax.persistence.query.timeout=180000
#keepaliveTime=600000
#spring.datasource.hikari.maximum-pool-size=3
#spring.datasource.hikari.minimum-idle=1
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.max-lifetime=600000
#spring.datasource.hikari.connection-timeout=30000


hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
hibernate.systemDate=SYSDATE
hibernate.multiTenancy=SCHEMA

hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
hibernate.generate_statistics=false
hibernate.temp.use_jdbc_metadata_defaults=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.datasource.hikari.leakDetectionThreshold=2000 // adjust based on your needs

jwt.secret=Zy9J5RjQ7mP0xNwL8fS2aVkH4tU6oYeC1rD3bG7qX9jK2mT5wF8zH0nL4pR6sV8
rememberme.key=jsfspring-sec
jwt.expiration=2592000000
jwt.refreshExpiration=604800000
