hibernate.connection.driver_class=oracle.jdbc.OracleDriver
hibernate.connection.dataSourceClassName=oracle.jdbc.pool.OracleDataSource
hibernate.connection.url=jdbc:oracle:thin:@//184.168.120.48:1521/lehaa.secureserver.net	
hibernate.connection.username=test_pay
hibernate.connection.password=test_pay


hibernate.hikari.minimumIdle=2
hibernate.hikari.maxLifetime=18000
# --1800000
hibernate.hikari.maximumPoolSize=5
hibernate.hikari.idleTimeout=600000
hibernate.hikari.connectionTimeout=30000
#120000
hibernate.hikari.validationTimeout=120000


#keepaliveTime=600000


hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
hibernate.systemDate=SYSDATE
hibernate.multiTenancy=SCHEMA